//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The4Dimension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The4Dimension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;shift_jis&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;isBigEndian Value=&quot;False&quot; /&gt;
        ///  &lt;BymlFormatVersion Value=&quot;1&quot; /&gt;
        ///  &lt;C1&gt;
        ///    &lt;C1 Name=&quot;Collision&quot;&gt;
        ///      &lt;A0 Name=&quot;Sensor&quot; StringValue=&quot;Collision&quot; /&gt;
        ///    &lt;/C1&gt;
        ///    &lt;C1 Name=&quot;Debug&quot;&gt;
        ///      &lt;A0 Name=&quot;NodeName&quot; StringValue=&quot;地形&quot; /&gt;
        ///    &lt;/C1&gt;
        ///    &lt;C1 Name=&quot;Executor&quot;&gt;
        ///      &lt;A0 Name=&quot;CategoryName&quot; StringValue=&quot;固定地形&quot; /&gt;
        ///    &lt;/C1&gt;
        ///    &lt;C1 Name=&quot;GroupClipping&quot;&gt;
        ///      &lt;D1 Name=&quot;MaxCount&quot; StringValue=&quot;64&quot; /&gt;
        ///    &lt;/C1&gt;
        ///    &lt;FF Name=&quot;Model&quot; StringValue=&quot;00000000&quot; /&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Actor {
            get {
                return ResourceManager.GetString("Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstStageMap1.szs
        ///CaveInkStageMap1.szs
        ///DownHillStageMap1.szs
        ///BalanceTruckStageMap1.szs
        ///KoopaFirstStageMap1.szs
        ///FieldWalkStageMap1.szs
        ///CavePatanStageMap1.szs
        ///DotCoinStageMap1.szs
        ///JumpFlipGeneratorStageMap1.szs
        ///BattleShipKillerStageMap1.szs
        ///DesertRuinStageMap1.szs
        ///AquariumSwimStageMap1.szs
        ///SkyChikuwaStageMap1.szs
        ///MountainRopeStageMap1.szs
        ///SweetsScrollStageMap1.szs
        ///FortressSpikeStageMap1.szs
        ///UpUpLandStageMap1.szs
        ///CaveClimbStageMap1.szs
        ///SkyRotateBlockStageMap1.szs
        ///FlashTeresaStageMap1.szs
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllStageList {
            get {
                return ResourceManager.GetString("AllStageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BaseModels {
            get {
                object obj = ResourceManager.GetObject("BaseModels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BCSTMtools {
            get {
                object obj = ResourceManager.GetObject("BCSTMtools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gbatemp {
            get {
                object obj = ResourceManager.GetObject("gbatemp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;shift_jis&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;isBigEndian Value=&quot;False&quot; /&gt;
        ///  &lt;BymlFormatVersion Value=&quot;1&quot; /&gt;
        ///  &lt;C1&gt;
        ///    &lt;C0 Name=&quot;CameraParams&quot;&gt;
        ///      
        ///    &lt;/C0&gt;
        ///    &lt;C1 Name=&quot;VisionParam&quot;&gt;
        ///      &lt;D2 Name=&quot;FarClipDistance&quot; StringValue=&quot;80000&quot; /&gt;
        ///      &lt;D2 Name=&quot;FovyDegree&quot; StringValue=&quot;45&quot; /&gt;
        ///      &lt;D2 Name=&quot;NearClipDistacne&quot; StringValue=&quot;100&quot; /&gt;
        ///      &lt;D2 Name=&quot;StereovisionDepth&quot; StringValue=&quot;0,4&quot; /&gt;
        ///      &lt;D2 Name=&quot;StereovisionDistance&quot; StringValue=&quot;200&quot; /&gt;
        ///    &lt;/C1&gt;
        ///  &lt;/C1&gt;
        ///&lt;/Root&gt;.
        /// </summary>
        internal static string GenericCameraParam {
            get {
                return ResourceManager.GetString("GenericCameraParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;shift_jis&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;isBigEndian Value=&quot;False&quot; /&gt;
        ///  &lt;BymlFormatVersion Value=&quot;1&quot; /&gt;
        ///  &lt;C0&gt;
        ///    &lt;C1&gt;
        ///      &lt;A0 Name=&quot;Name&quot; StringValue=&quot;SePmShootFire&quot; /&gt;
        ///      &lt;A0 Name=&quot;Type&quot; StringValue=&quot;SoundItem&quot; /&gt;
        ///    &lt;/C1&gt;
        ///  &lt;/C0&gt;
        ///&lt;/Root&gt;.
        /// </summary>
        internal static string GenericPreloadList {
            get {
                return ResourceManager.GetString("GenericPreloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;shift_jis&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;isBigEndian Value=&quot;False&quot; /&gt;
        ///  &lt;BymlFormatVersion Value=&quot;1&quot; /&gt;
        ///  &lt;C1&gt;
        ///    &lt;C0 Name=&quot;FootPrint&quot;&gt;
        ///      &lt;C1&gt;
        ///        &lt;A0 Name=&quot;Material&quot; StringValue=&quot;Sand&quot; /&gt;
        ///        &lt;A0 Name=&quot;Model&quot; StringValue=&quot;FootPrint&quot; /&gt;
        ///      &lt;/C1&gt;
        ///    &lt;/C0&gt;
        ///    &lt;D1 Name=&quot;StageTimer&quot; StringValue=&quot;500&quot; /&gt;
        ///    &lt;D1 Name=&quot;StageTimerRestart&quot; StringValue=&quot;300&quot; /&gt;
        ///  &lt;/C1&gt;
        ///&lt;/Root&gt;.
        /// </summary>
        internal static string GenericStageInfo {
            get {
                return ResourceManager.GetString("GenericStageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///Title CCNT patcher
        ///cls
        ///echo This will add the object entries to the CreatorClassNameTable.szs file.
        ///echo You should make a backup of this file.
        ///echo Press enter to continue
        ///pause &gt;nul
        ///Start /W Patcher.exe CCNTpatch Done, you are ready to go !
        ///del 3DS.dll
        ///del CCNTpatch.xml
        ///del CommonCompressors.dll
        ///del CommonFiles.dll
        ///del LibEveryFileExplorer.dll
        ///del NDS.dll
        ///del Patcher.exe
        ///del &quot;Patch script.bat&quot;.
        /// </summary>
        internal static string PatchScript {
            get {
                return ResourceManager.GetString("PatchScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;shift_jis&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;isBigEndian Value=&quot;False&quot; /&gt;
        ///  &lt;BymlFormatVersion Value=&quot;1&quot; /&gt;
        ///  &lt;C0&gt;
        ///    &lt;C1&gt;
        ///      &lt;A0 Name=&quot;Name&quot; StringValue=&quot;Collision&quot; /&gt;
        ///      &lt;A0 Name=&quot;Type&quot; StringValue=&quot;CollisionParts&quot; /&gt;
        ///    &lt;/C1&gt;
        ///  &lt;/C0&gt;
        ///&lt;/Root&gt;.
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon t4d {
            get {
                object obj = ResourceManager.GetObject("t4d", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
