//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The4Dimension.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GamePath {
            get {
                return ((string)(this["GamePath"]));
            }
            set {
                this["GamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnlyKnownObjs {
            get {
                return ((bool)(this["OnlyKnownObjs"]));
            }
            set {
                this["OnlyKnownObjs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.92")]
        public double CameraInertia {
            get {
                return ((double)(this["CameraInertia"]));
            }
            set {
                this["CameraInertia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFps {
            get {
                return ((bool)(this["ShowFps"]));
            }
            set {
                this["ShowFps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTriCount {
            get {
                return ((bool)(this["ShowTriCount"]));
            }
            set {
                this["ShowTriCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDbgInfo {
            get {
                return ((bool)(this["ShowDbgInfo"]));
            }
            set {
                this["ShowDbgInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStartup {
            get {
                return ((bool)(this["FirstStartup"]));
            }
            set {
                this["FirstStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CameraMode {
            get {
                return ((int)(this["CameraMode"]));
            }
            set {
                this["CameraMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ZoomSen {
            get {
                return ((double)(this["ZoomSen"]));
            }
            set {
                this["ZoomSen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RotSen {
            get {
                return ((double)(this["RotSen"]));
            }
            set {
                this["RotSen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoMoveCam {
            get {
                return ((bool)(this["AutoMoveCam"]));
            }
            set {
                this["AutoMoveCam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddObjectOrigin {
            get {
                return ((bool)(this["AddObjectOrigin"]));
            }
            set {
                this["AddObjectOrigin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/KirbysDarkNebula/T4D/master/newobjdb.xml")]
        public string DownloadDbLink {
            get {
                return ((string)(this["DownloadDbLink"]));
            }
            set {
                this["DownloadDbLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckUpdates {
            get {
                return ((bool)(this["CheckUpdates"]));
            }
            set {
                this["CheckUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadDb {
            get {
                return ((bool)(this["DownloadDb"]));
            }
            set {
                this["DownloadDb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomMusic {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomMusic"]));
            }
            set {
                this["CustomMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>STM_BGM_AFTER_BOSS</string>\r\n  <string>STM_BGM_BOSS_BUNBUN</string>\r\n  <st" +
            "ring>STM_BGM_BOSS_PUNPUN</string>\r\n  <string>STM_BGM_CASTLE_A</string>\r\n  <strin" +
            "g>STM_BGM_COURSE_SELECT</string>\r\n  <string>STM_BGM_DEMO01_A</string>\r\n  <string" +
            ">STM_BGM_DEMO01_B</string>\r\n  <string>STM_BGM_DEMO02_A</string>\r\n  <string>STM_B" +
            "GM_DEMO02_B</string>\r\n  <string>STM_BGM_DEMO03_A</string>\r\n  <string>STM_BGM_DEM" +
            "O03_B</string>\r\n  <string>STM_BGM_DEMO04_A</string>\r\n  <string>STM_BGM_DEMO04_B<" +
            "/string>\r\n  <string>STM_BGM_DEMO05</string>\r\n  <string>STM_BGM_ENDING</string>\r\n" +
            "  <string>STM_BGM_GOAL_01</string>\r\n  <string>STM_BGM_GOAL_02</string>\r\n  <strin" +
            "g>STM_BGM_GOAL_03</string>\r\n  <string>STM_BGM_GOAL_03_B</string>\r\n  <string>STM_" +
            "BGM_HURRY_UP</string>\r\n  <string>STM_BGM_JG_COURSEIN</string>\r\n  <string>STM_BGM" +
            "_JG_GAME_OVER</string>\r\n  <string>STM_BGM_JG_MISS</string>\r\n  <string>STM_BGM_KI" +
            "NOHOUSE</string>\r\n  <string>STM_BGM_KOOPA_01</string>\r\n  <string>STM_BGM_KOOPA_0" +
            "2</string>\r\n  <string>STM_BGM_MUTEKISTAR</string>\r\n  <string>STM_BGM_POTER</stri" +
            "ng>\r\n  <string>STM_BGM_RAREROOM</string>\r\n  <string>STM_BGM_STAFF_ROLL</string>\r" +
            "\n  <string>STM_BGM_TRUCK_A</string>\r\n  <string>STM_BGM_WORLD1_A</string>\r\n  <str" +
            "ing>STM_BGM_WORLD2_A</string>\r\n  <string>STM_BGM_WORLD3_A</string>\r\n  <string>ST" +
            "M_BGM_WORLD4_A</string>\r\n  <string>STM_BGM_WORLD5_A</string>\r\n  <string>STM_BGM_" +
            "WORLD6_A</string>\r\n  <string>STM_BGM_WORLD7_A</string>\r\n  <string>STM_BGM_WORLD8" +
            "_A</string>\r\n  <string>STM_BGM_WORLD8S_A</string>\r\n  <string>STM_BGM_WORLD1_B</s" +
            "tring>\r\n  <string>STM_BGM_WORLD2_B</string>\r\n  <string>STM_BGM_WORLD3_B</string>" +
            "\r\n  <string>STM_BGM_WORLD4_B</string>\r\n  <string>STM_BGM_WORLD5_B</string>\r\n  <s" +
            "tring>STM_BGM_WORLD6_B</string>\r\n  <string>STM_BGM_WORLD7_B</string>\r\n  <string>" +
            "STM_BGM_WORLD8_B</string>\r\n  <string>STM_BGM_WORLD8S_B</string>\r\n  <string>STM_J" +
            "G_KINO_GIFT_GOLD</string>\r\n  <string>STM_JG_KINO_GIFT_SILVER</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection Music {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Music"]));
            }
            set {
                this["Music"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DotComma {
            get {
                return ((bool)(this["DotComma"]));
            }
            set {
                this["DotComma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HasAA {
            get {
                return ((bool)(this["HasAA"]));
            }
            set {
                this["HasAA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextFilter {
            get {
                return ((int)(this["TextFilter"]));
            }
            set {
                this["TextFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection OpenRecent {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OpenRecent"]));
            }
            set {
                this["OpenRecent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public double CamSpeed {
            get {
                return ((double)(this["CamSpeed"]));
            }
            set {
                this["CamSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double CamDistance {
            get {
                return ((double)(this["CamDistance"]));
            }
            set {
                this["CamDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDesignSound {
            get {
                return ((bool)(this["UseDesignSound"]));
            }
            set {
                this["UseDesignSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExperimentalFeatures {
            get {
                return ((bool)(this["ExperimentalFeatures"]));
            }
            set {
                this["ExperimentalFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowChildren {
            get {
                return ((bool)(this["ShowChildren"]));
            }
            set {
                this["ShowChildren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCamSettings {
            get {
                return ((bool)(this["UseCamSettings"]));
            }
            set {
                this["UseCamSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BackfaceCull {
            get {
                return ((bool)(this["BackfaceCull"]));
            }
            set {
                this["BackfaceCull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LayeredFSPath {
            get {
                return ((string)(this["LayeredFSPath"]));
            }
            set {
                this["LayeredFSPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLayeredFs {
            get {
                return ((bool)(this["UseLayeredFs"]));
            }
            set {
                this["UseLayeredFs"] = value;
            }
        }
    }
}
